name:                london-tube-lines-hs
version:             0.1.0.0
github:              "rachel-barrett/london-tube-lines-hs"
license:             BSD3
author:              "Rachel Barrett"
maintainer:          "rachel_barrett@live.co.uk"
copyright:           "2020 Rachel Barrett"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-example#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- record-dot-preprocessor
- record-hasfield
- sqlite-simple
- servant-swagger
- swagger2
- lens

library:
  source-dirs: src

executables:
  servant-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - london-tube-lines-hs

tests:
  servant-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - london-tube-lines-hs
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
